# Generated by Django 2.1.2 on 2019-04-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amenities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adults', models.IntegerField()),
                ('Child', models.IntegerField()),
                ('Infant', models.IntegerField()),
                ('Fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Stars', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_1', models.CharField(max_length=100)),
                ('Street_2', models.CharField(max_length=100)),
                ('City_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.City')),
            ],
        ),
        migrations.CreateModel(
            name='Key_Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Per_Day', models.IntegerField()),
                ('Hotel_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price_Per_Person', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Sutaible_For', models.CharField(max_length=255)),
                ('Transport_Mode', models.CharField(max_length=255)),
                ('City_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.City')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.City')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.City')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Night', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('Cities', models.ManyToManyField(to='package.City')),
                ('Keys', models.ManyToManyField(to='package.Key_Features')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trip_package',
            name='Staring',
            field=models.ManyToManyField(to='package.Week'),
        ),
        migrations.AddField(
            model_name='trip_origin',
            name='Package_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.Trip_Package'),
        ),
        migrations.AddField(
            model_name='trip_destination',
            name='Package_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.Trip_Package'),
        ),
        migrations.AddField(
            model_name='package_details',
            name='Activities',
            field=models.ManyToManyField(to='package.Total_Activities'),
        ),
        migrations.AddField(
            model_name='package_details',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.City'),
        ),
        migrations.AddField(
            model_name='package_details',
            name='Hotel_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Hotel'),
        ),
        migrations.AddField(
            model_name='package_details',
            name='Package_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Trip_Package'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Hotel_Address'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Amenities',
            field=models.ManyToManyField(to='package.Amenities'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='Activity_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Total_Activities'),
        ),
        migrations.AddField(
            model_name='extra_activity',
            name='Activity_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Total_Activities'),
        ),
        migrations.AddField(
            model_name='extra_activity',
            name='Booking_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Trip_Package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Package_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Trip_Package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='User_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
