# Generated by Django 2.2 on 2019-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
