# Generated by Django 2.2 on 2019-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190413_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_activities',
            name='Activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='total_activities',
            name='Sutaible_For',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='total_activities',
            name='Transport_Mode',
            field=models.CharField(max_length=100),
        ),
    ]
