# Generated by Django 2.2 on 2019-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20190413_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='amenities',
            name='Amenities',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='Country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='State',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='key_features',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package_details',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='total_activities',
            name='Activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='total_activities',
            name='Sutaible_For',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='total_activities',
            name='Transport_Mode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip_package',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='trip_package',
            name='Staring',
            field=models.ManyToManyField(to='package.Week'),
        ),
    ]
